root: true
extends:
  - standard
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
rules:
  semi:
    - warn
    - never
  comma-dangle:
    - warn
    - always-multiline
