root: true
extends:
  - standard
  # - eslint:recommended
  - plugin:@typescript-eslint/recommended
plugins:
  - "@typescript-eslint"
  - jest
env:
  jest/globals: true
  es2021: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
overrides:
  - files:
      - "**/*.test.ts"
    extends:
      - 'plugin:@typescript-eslint/disable-type-checked'
    rules:
      '@typescript-eslint/ban-ts-comment': off
rules:
  semi:
    - warn
    - never
  comma-dangle:
    - warn
    - always-multiline
