name: "All Green Checks"
description: "Action to verify run checks"
author: "Pedro Silva"

inputs:
  ignore-jobs:
    description: "Jobs to ignore checking, separated by comma or new line"
    default: ${{ github.job }}
    required: true
  check-interval:
    description: "Interval between checks in seconds"
    default: "30"
    required: true
  ref:
    description: "Ref to check the status"
    default: ${{ github.event.pull_request.head.sha || github.sha }}
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_IGNORE-JOBS: ${{ inputs.ignore-jobs }}
    INPUT_CHECK-INTERVAL: ${{ inputs.check-interval }}
    INPUT_REF: ${{ inputs.ref }}
