name: Code quality checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
